### ISSUE TITLE
정보 리스트 수정

### ISSUE THREAD

**Issue by oajh04** [DSM-PICK/PICK2021-ADMIN-CLIENT#53]
## Description

> 정보 리스트 수정

## issue 종류

- [ ] 기능추가
- [x] 기능수정
- [ ] 버그수정
- [ ] 세팅

## Todo

- [x] 선생님 리스트 박스 수정
- [x] 장소 리스트 박스 생성
- [x] 학생 리스트 박스 수정
